INSERT INTO education_levels(education, created_at, updated_at) VALUES 
('Bachelors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Masters', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Doctorate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO position_types(position, created_at, updated_at) VALUES 
('Part-Time', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Full-Time', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Internship', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Contract', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Post-Doc', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PhD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO position_areas(area, created_at, updated_at) VALUES 
('Research', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO employment_classes(classification, created_at, updated_at) VALUES 
('Research Lab', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Academia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Government', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Industry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Startup', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);